--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';

--
-- Name: device; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.device (
    id integer NOT NULL,
    name character varying,
    uuid uuid NOT NULL
);


ALTER TABLE public.device OWNER TO admin;

--
-- Name: device_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecef; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ecef (
    id bigint NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    x_coordinate double precision NOT NULL,
    y_coordinate double precision NOT NULL,
    z_coordinate double precision NOT NULL,
    device_id integer NOT NULL
);


ALTER TABLE public.ecef OWNER TO admin;

--
-- Name: ecef_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.ecef ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecef_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: llh; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.llh (
    id bigint NOT NULL,
    "timestamp" timestamp without time zone,
    device_id integer NOT NULL,
    geography_position public.geography NOT NULL
);


ALTER TABLE public.llh OWNER TO admin;

--
-- Name: llh_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.llh ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.llh_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device device_pk; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_pk PRIMARY KEY (id);


--
-- Name: device device_unique; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT device_unique UNIQUE (uuid);


--
-- Name: ecef ecef_pk; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ecef
    ADD CONSTRAINT ecef_pk PRIMARY KEY (id);


--
-- Name: llh llh_pk; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.llh
    ADD CONSTRAINT llh_pk PRIMARY KEY (id);


--
-- Name: ecef_timestamp_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX ecef_timestamp_idx ON public.ecef USING btree ("timestamp");


--
-- Name: llh_timestamp_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX llh_timestamp_idx ON public.llh USING btree ("timestamp");


--
-- Name: ecef ecef_device_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ecef
    ADD CONSTRAINT ecef_device_fk FOREIGN KEY (device_id) REFERENCES public.device(id);


--
-- Name: llh llh_device_fk; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.llh
    ADD CONSTRAINT llh_device_fk FOREIGN KEY (device_id) REFERENCES public.device(id);



